services:
  postgres:
    container_name: "postgres"
    hostname: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=pso
      - POSTGRES_PASSWORD=pso
      - POSTGRES_DB=pso
